### ISSUE TITLE
Suggestion for signature

### ISSUE THREAD

**Issue by haiduong87** [usercode/ImageWizard#10]
Hi @usercode,

Can we allow to sign only 2 parts of the url?

Example:
- signed url: https://localhost/image/cGiAwFYGYWx0SzO0YyCidWIfkdlUYrVgBwbm7bcTOjE/resize(200,200)/grayscale()/jpg(90)/fetch/https://upload.wikimedia.org/wikipedia/commons/b/b7/Europe_topography_map.png
- un-signed: https://localhost/image/resize(200,200)/grayscale()/jpg(90)/fetch/https://upload.wikimedia.org/wikipedia/commons/b/b7/Europe_topography_map.png
- new un-signed: https://localhost/image/fetch/https://upload.wikimedia.org/wikipedia/commons/b/b7/Europe_topography_map.png

We just sign "loader type" and "loader source" make the "filters" part free to use.

When signing url via api:
- Add option to sign 2 parts
- Add a dot (".") to any place of the signature

When validating:
- Just check the dot (".") to do the validation.
- We can also apply rate limit for the new one (Example: user can make up to 1000 different filters per day)

This may affect the cache strategy.

Thanks,

Duong

**Comment by usercode** [comment]
Hi Duong,

this is a very special case why I can't add an options for this.

But you can inherits from HMACSHA256UrlSignature and override the method GetUrlValue. Instead of returning the full path. you can use $"{url.LoaderType}/{url.LoaderSource}".

https://github.com/usercode/ImageWizard/blob/dd12c5ea26b1fdb5223a09d4be9af6942b5b53e2/src/ImageWizard.Utils/Signature/HMACSHA256UrlSignature.cs#L44-L47

New nuget packages coming soon..

**Comment by usercode** [comment]
NuGet packages are published.
