### ISSUE TITLE
UseUnsafeUrl remove 'unsafe' from url?

### ISSUE THREAD

**Issue by dotnetshadow** [usercode/ImageWizard#5]
Firstly a great library, well done.

1) I was wondering when using the `UseUnsafeUrl `set to true, is there a way for the **unsafe** word to be removed from the url?
`https://localhsot:5001/image/unsafe/....` to `https://localhsot:5001/image/....` ?

**Comment by usercode** [comment]
> Firstly a great library, well done.
Thanks :smiley:

> 1. I was wondering when using the `UseUnsafeUrl `set to true, is there a way for the **unsafe** word to be removed from the url?
>    `https://localhsot:5001/image/unsafe/....` to `https://localhsot:5001/image/....` ?

You should never use the unsafe mode because of url tampering especially for public services. 

But if you use the unsafe mode, you should see every time that your urls are unsafe. Thats the reason.

**Comment by intoccabil** [comment]
@usercode Thanks for the great project. Can you elaborate somewhere how the hash is generated and whether it is possible to generate it in other way than using the client library? I've read the code and understood that the hash is being generated using the image path and a secret key, is it possible to generate hashes from the front-end spa, for instance?

I am asking this because consider a following scenario:

I have some objects in the database that have an ImageUrl field, that contains an (duh) url to the image. I am serving the objects via an azure search index, because there are millions of these objects and using the db is too slow. The objects get into the index via a SQL view. So, using the view, I am unable to generate hashes to resize the images, because I'm not sure I can replicate the hash algo in SQL. Is there an obvious solution to this case, that I'm missing?

**Comment by usercode** [comment]
The signature based on HMACSHA256 . You can find the source here:

https://github.com/usercode/ImageWizard/blob/a0bc5a6bd208765b996123fe3ba3c4711bd51406/src/ImageWizard.Utils/CryptoService.cs#L45-L50

But it's absolute no good idea to generate the siganture by a client app. If the client app contains the secret key, your security is broken.

Maybe this is an alternate way:
If your app has an user login, you can add the authorization policy to the imagewizard endpoint.

> I'm not sure I can replicate the hash algo in SQL. Is there an obvious solution to this case, that I'm missing?

I don't understand, why you want to put the siganture into azure. Caching of transformed images is the job of imagewizard. You can create your own ImageCache to handle this. (IImageCache delivers all metadata like signature.)

https://github.com/usercode/ImageWizard/blob/a0bc5a6bd208765b996123fe3ba3c4711bd51406/src/ImageWizard.Core/ImageCaches/IImageCache.cs#L14-L31

Or you can use the AzureBlobLoader to load the original images from azure.

The signature is just for allowing trusted clients to use the imagewizard middleware. All other components like image cache and image loader should not have a reference to the signature. (The signature can be changed.)
